# Generated by Django 4.2.1 on 2023-05-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.FileField(blank=True, upload_to='uploads'),
        ),
        migrations.AddField(
            model_name='post',
            name='media_url',
            field=models.URLField(blank=True),
        ),
    ]
