# Generated by Django 4.2.1 on 2023-05-24 13:45

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nest', '0002_remove_post_image_post_media_post_media_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media_url',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
