# Generated by Django 4.2.1 on 2023-05-24 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nest', '0003_alter_post_media_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='media_url',
            new_name='video',
        ),
    ]
